apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        version: "v1.0"
    spec:
      containers:
        #backend container
        - name: backend-container
          image: maurizb/guess-game-k8s-backend:latest
          ports:
          - containerPort: 5000
          env:
          - name: FLASK_DB_HOST
            value: db
          - name: FLASK_DB_PASSWORD
            value: secretpass
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000