
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        version: "v1.0"
    spec:
      containers: 
      #db container
      - name: database-container
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: secretpass
        volumeMounts:
        - name: my-db-backup
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: my-db-backup
        persistentVolumeClaim:
          claimName: my-db-backup
---
#define volumes
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-db-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi