#deployment, criar um serviço???
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        version: "v1.0"
    spec:
      containers:
      #nginx container
      - name: nginx-container
        image: nginx:1.27 
        ports:
        - containerPort: 80
      # backend container
      - name: backend-container
        image: python:3.9-slim
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_DB_HOST
          value: database
      # database container
      - name: database-container
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: secretpass
        volumeMounts:
        - name: my-db-backup
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: my-db-backup
        persistentVolumeClaim:
          claimName: my-db-backup
      # define restart policy para todos containers
      restartPolicy: Always
  # estratégia de rollout
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---
#define volumes
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-db-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#service
#apiVersion: v1
#Kind: Service
#metadata:
#  name: myapp-service
#  labels:
#    app: myapp
#spec:
#  selector:
#    app: myapp
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 80
#  type: LoadBalancer